[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
gloo-net = "^0.6" 
wasm-bindgen-futures = "^0.4"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.26"