[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
reqwest = { version = "^0.12", features = ["json", "wasm"] }
wasm-bindgen-futures = "^0.4"
serde = { version = "1.0", features = ["derive"] }
